import { StyleSheet, Platform } from 'react-native';

export const orphanStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  scrollContent: {
    paddingBottom: 30,
  },
  header: {
    paddingTop: 60,
    paddingBottom: 30,
    paddingHorizontal: 25,
    backgroundColor: '#0077cc',
    borderBottomLeftRadius: 35,
    borderBottomRightRadius: 35,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
  },
  headerTextContainer: {
    flex: 1,
  },
  welcomeText: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.8)',
    fontWeight: '500',
  },
  nameText: {
    fontSize: 26,
    color: '#fff',
    fontWeight: '800',
    marginTop: 2,
  },
  logoutButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    paddingHorizontal: 20,
    marginTop: 25,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1e293b',
    marginBottom: 15,
    letterSpacing: 0.5,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 22,
    marginBottom: 25,
    elevation: 4,
    shadowColor: '#64748b',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
  },
  feeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  feeInfo: {
    flex: 1,
  },
  feeTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#334155',
  },
  feeAmount: {
    fontSize: 14,
    color: '#64748b',
    marginTop: 2,
    fontWeight: '600',
  },
  feeStatus: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    overflow: 'hidden',
    fontSize: 11,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  statusPending: {
    backgroundColor: '#fff7ed',
    color: '#f59e0b',
  },
  statusPaid: {
    backgroundColor: '#f0fdf4',
    color: '#22c55e',
  },
  inputGroup: {
    marginBottom: 15,
  },
  label: {
    fontSize: 14,
    fontWeight: '700',
    color: '#475569',
    marginBottom: 8,
    marginLeft: 4,
  },
  input: {
    backgroundColor: '#f8fafc',
    borderRadius: 15,
    padding: 16,
    fontSize: 15,
    color: '#1e293b',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  submitButton: {
    backgroundColor: '#0077cc',
    borderRadius: 18,
    padding: 18,
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#0077cc',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
  },
  emptyText: {
    color: '#94a3b8',
    fontStyle: 'italic',
    textAlign: 'center',
    marginTop: 10,
  },
  aidScroller: {
    marginTop: 10,
    marginBottom: 20,
    paddingLeft: 5,
  },
  aidCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 15,
    marginRight: 15,
    width: 220,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    borderLeftWidth: 5,
    borderLeftColor: '#33cc99',
  },
  donorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  donorAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  donorInitial: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0077cc',
  },
  donorName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  aidTime: {
    fontSize: 11,
    color: '#999',
  },
  aidDetail: {
    backgroundColor: '#f0fdf4',
    padding: 10,
    borderRadius: 12,
    marginBottom: 12,
  },
  aidType: {
    fontSize: 10,
    fontWeight: '800',
    color: '#16a34a',
    letterSpacing: 0.5,
  },
  aidQty: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 2,
  },
  thanksBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#e6f4ff',
  },
  thanksBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0077cc',
    marginLeft: 6,
  },
  emptyAidCard: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 15,
    width: 300,
    alignItems: 'center',
  },
  sectionSub: {
    fontSize: 14,
    color: '#666',
    marginLeft: 5,
    marginTop: -10,
    marginBottom: 10,
  },
  feeCard: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#f1c40f',
  },
  feeDate: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  feeRight: {
    alignItems: 'flex-end',
  },
  statusText: {
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 4,
  },
  statusPledged: { color: '#3498db' },
  badgeCount: {
    backgroundColor: '#ff4444',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  badgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  typeSelector: {
    flexDirection: 'row',
    marginBottom: 15,
    justifyContent: 'space-between',
  },
  typeBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 15,
    backgroundColor: '#f5f7fa',
    borderWidth: 1,
    borderColor: '#e1e5eb',
  },
  typeBtnSelected: {
    backgroundColor: '#4da6ff',
    borderColor: '#4da6ff',
  },
  typeBtnText: {
    fontSize: 12,
    color: '#666',
  },
  typeBtnTextSelected: {
    color: '#fff',
    fontWeight: 'bold',
  },
  orphanageList: {
    marginBottom: 20,
  },
  orphanageItem: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e1e5eb',
  },
  orphanageItemActive: {
    borderColor: '#4da6ff',
    backgroundColor: '#4da6ff10',
  },
  orphanageName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  orphanageNameActive: {
    color: '#0077cc',
  },
  orphanageCity: {
    fontSize: 12,
    color: '#777',
    marginTop: 2,
  },
  filePicker: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#e1e5eb',
    borderStyle: 'dashed',
  },
  filePickerText: {
    marginLeft: 10,
    fontSize: 14,
    color: '#4da6ff',
    fontWeight: '600',
  },
  regHeader: {
    paddingTop: 50,
    paddingBottom: 30,
    paddingHorizontal: 30,
    backgroundColor: '#fff',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    alignItems: 'center',
    marginBottom: 20,
  },
  regTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  regSub: {
    fontSize: 16,
    color: '#777',
    marginTop: 8,
  },
  formSection: {
    backgroundColor: '#fff',
    borderRadius: 25,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  genderBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#f5f7fa',
    alignItems: 'center',
    marginHorizontal: 5,
    borderWidth: 1,
    borderColor: '#e1e5eb',
  },
  genderBtnActive: {
    backgroundColor: '#0077cc',
    borderColor: '#0077cc',
  },
  genderBtnText: {
    color: '#666',
    fontWeight: '600',
  },
  genderBtnTextActive: {
    color: '#fff',
  },
  orphanageListContainer: {
    marginTop: 10,
  },
  orgCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#f8fafc',
    borderRadius: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  orgCardActive: {
    borderColor: '#0077cc',
    backgroundColor: '#f0f9ff',
  },
  orgName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#334155',
  },
  orgNameActive: {
    color: '#0077cc',
  },
  orgCity: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  pickerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f9ff',
    padding: 18,
    borderRadius: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#0077cc',
    borderStyle: 'dashed',
  },
  pickerBtnActive: {
    backgroundColor: '#0077cc',
    borderStyle: 'solid',
  },
  pickerBtnText: {
    marginLeft: 12,
    fontSize: 14,
    color: '#0077cc',
    fontWeight: '700',
  },
  pickerBtnTextActive: {
    color: '#fff',
  },
  primarySubmitBtn: {
    backgroundColor: '#0077cc',
    height: 60,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#0077cc',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  primarySubmitBtnText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  btnDisabled: {
    opacity: 0.6,
  },
  cancelLink: {
    marginTop: 25,
    alignItems: 'center',
    paddingBottom: 20,
  },
  cancelLinkText: {
    color: '#64748b',
    fontSize: 14,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  settingsButton: {
    position: 'absolute',
    right: 70,
    top: 40,
    padding: 10,
    backgroundColor: '#fff',
    borderRadius: 12,
    zIndex: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  avatarContainer: {
    marginTop: 0,
    marginBottom: 15,
    borderRadius: 50,
    padding: 3,
    backgroundColor: '#fff',
    shadowColor: '#0077cc',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 2,
    borderColor: '#0077cc',
  },
  avatarPlaceholder: {
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  editModalContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 25,
    maxHeight: '85%',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  editAvatarContainer: {
    alignSelf: 'center',
    marginVertical: 20,
    position: 'relative',
  },
  editAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#f1f5f9',
  },
  editIconBadge: {
    position: 'absolute',
    bottom: 0,
    right: 5,
    backgroundColor: '#0077cc',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  addMiniBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0077cc',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  addMiniBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  progThumb: {
    width: 50,
    height: 50,
    borderRadius: 10,
    backgroundColor: '#f1f5f9',
  },
  progThumbPlaceholder: {
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  deleteCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fff1f1',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
  },
  progPreview: {
    width: '100%',
    height: 150,
    borderRadius: 15,
    marginBottom: 15,
    resizeMode: 'cover',
  },
  viewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 10,
  },
  viewBack: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewBackText: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  addFullBtn: {
    backgroundColor: '#0077cc',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 12,
  },
  addFullBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    marginLeft: 6,
    fontSize: 14,
  },
  viewTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  viewSub: {
    fontSize: 14,
    color: '#777',
    marginBottom: 20,
  },
  emptyView: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
    backgroundColor: '#fff',
    borderRadius: 20,
    marginTop: 20,
  },
  emptyViewText: {
    textAlign: 'center',
    color: '#94a3b8',
    marginTop: 15,
    fontSize: 14,
  },
  progThumbLarge: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
  },
  deleteCircleLarge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#fff1f1',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  statusBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#fff',
  },
  statusPendingBg: {
    backgroundColor: '#f59e0b',
  },
  statusApprovedBg: {
    backgroundColor: '#10b981',
  },
  statusFulfilledBg: {
    backgroundColor: '#3b82f6',
  },
});
